# YAML for MS-hosted Selenium + WebDriver

trigger: none

pool:
  vmImage: windows-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'
  
- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: pip install selenium
  displayName: 'Install Selenium'

- script: pip install webdriver-manager
  displayName: 'Install wedriver-manager'

- script: pip install packaging
  displayName: 'Install packaging'

  
- task: PythonScript@0
  displayName: Login & Change Auxiliar
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'newLogin.py'
